- name: configure backend server
  hosts: backend
  become: yes
  tasks:
  - name: disable current Nodejs vresion
    ansible.builtin.command: "dnf module disable nodejs -y"

  - name: enable Nodejs v20
    ansible.builtin.command: "dnf module enable nodejs:20 -y"

  - name: install Nodejs
    ansible.builtin.package:
      name: nodejs
      state: installed

  - name: Add user
    ansible.builtin.user:
      name: expense

  - name: Create App directory 
    ansible.builtin.file:
      path: /app
      state: directory