- name: configure backend server
  hosts: backend
  become: yes
  tasks:
  - name: disable current nodejs vresion
    ansible.builtin.command: "dnf module disable nodejs -y"

  # - name: enable nodejs v20
  #   ansible.builtin.command: "dnf module enable nodejs:20 -y"