- name: configure frontend server
  hosts: frontend
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present

  - name: start and enable nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

  - name: delate html file
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent

  - name: create html file
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory




  # - name: Download backend code
  #   ansible.builtin.get_url:
  #     url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
  #     dest: /tmp/backend.zip